name: Update README

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   schedule:
  #     - cron: '0 0 * * *' # Run every day at 00:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use your PAT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script to update README
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README tables"
          git push
